version: "3.7"

services:
  # MongoDB
  cadmus-chgc-mongo:
    image: mongo
    container_name: cadmus-chgc-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    networks:
      - cadmus-chgc-network

  # MySql
  cadmus-chgc-mysql:
    image: mysql:8.0.30
    container_name: cadmus-chgc-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - cadmus-chgc-network

  # API
  cadmus-chgc-api:
    image: vedph2020/cadmus-chgc-api:0.0.2
    container_name: cadmus-chgc-api
    ports:
      - 5078:80
    depends_on:
      - cadmus-chgc-mongo
      - cadmus-chgc-mysql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-chgc-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-chgc-mysql;port=3306;Database={0};Uid=root;Pwd=mysql
      - SEED__INDEXDELAY=0
      - SEED__ITEMCOUNT=0
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-chgc-mongo:27017/cadmus-logs
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-chgc-network

  # app
  cadmus-chgc-app:
    image: vedph2020/cadmus-chgc-app:0.0.2
    container_name: cadmus-chgc-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-chgc-api
    networks:
      - cadmus-chgc-network

networks:
  cadmus-chgc-network:
    driver: bridge
